image: node:15 # Choose an image matching your project needs

pipelines: # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
    default:
      - step: 
          script:
              - npm install
              - npm build